// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATJgv2AzUyOuEwWRi9dB9YypllDxR7uoE',
    appId: '1:469738442216:web:28a86d5c67a40f55d8685d',
    messagingSenderId: '469738442216',
    projectId: 'allergygenieb2',
    authDomain: 'allergygenieb2.firebaseapp.com',
    storageBucket: 'allergygenieb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANio6Esrtfbo4vU-FOjMFKvpWsOZclewA',
    appId: '1:469738442216:android:e2c8a86b1f8f9a91d8685d',
    messagingSenderId: '469738442216',
    projectId: 'allergygenieb2',
    storageBucket: 'allergygenieb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9UhtTEqs7ytM2ckuOxL2DoS8ZB8bdrYA',
    appId: '1:469738442216:ios:31ad68f196e0847dd8685d',
    messagingSenderId: '469738442216',
    projectId: 'allergygenieb2',
    storageBucket: 'allergygenieb2.appspot.com',
    iosBundleId: 'com.example.calendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9UhtTEqs7ytM2ckuOxL2DoS8ZB8bdrYA',
    appId: '1:469738442216:ios:c68f9c0b935df2aed8685d',
    messagingSenderId: '469738442216',
    projectId: 'allergygenieb2',
    storageBucket: 'allergygenieb2.appspot.com',
    iosBundleId: 'com.example.calendar.RunnerTests',
  );
}
